[tool.poetry]
name = "project"
version = "0.1.0"
description = "Translator"
authors = ["Andrey Knyazhev"]
license = "No License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt5 = "^5.15.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
